DROP TABLE IF EXISTS samples;

CREATE TABLE IF NOT EXISTS samples
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR(255) NOT NULL,
    age    INTEGER      NOT NULL,
    status VARCHAR(20)  NOT NULL
);

DROP TABLE IF EXISTS certificates;

CREATE TABLE IF NOT EXISTS certificates
(
    id                 UUID          NOT NULL PRIMARY KEY,
    alias              VARCHAR(128)  NOT NULL,
    subject            VARCHAR(1024) NOT NULL,
    issuer             VARCHAR(1024) NOT NULL,
    serial_number      VARCHAR(128)  NOT NULL,
    not_before         TIMESTAMP     NOT NULL,
    not_after          TIMESTAMP     NOT NULL,
    status             VARCHAR(20)   NOT NULL,
    pem_content        CLOB          NOT NULL,
    fingerprint        VARCHAR(128)  NOT NULL,
    key_usage          VARCHAR(1024) NOT NULL DEFAULT '',
    subject_alt_names  VARCHAR(2048) NOT NULL DEFAULT '',
    created_at         TIMESTAMP     NOT NULL,
    updated_at         TIMESTAMP     NOT NULL,
    CONSTRAINT uq_certificates_fingerprint UNIQUE (fingerprint)
);
