# SampleStatus
enum.SampleStatus.ACTIVE=\uD65C\uC131
enum.SampleStatus.INACTIVE=\uBE44\uD65C\uC131
enum.SampleStatus.SUSPENDED=\uC815\uC9C0

# CertificateStatus
enum.CertificateStatus.PENDING=\uB300\uAE30
enum.CertificateStatus.VALID=\uC720\uD6A8
enum.CertificateStatus.EXPIRED=\uB9CC\uB8CC
enum.CertificateStatus.REVOKED=\uD3D0\uAE30
